name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jackpeterwell
          password: 321be62c-e1f6-40d3-8806-1f5c7a4ef1d6

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: jackpeterwell/busybox:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
